### PR TITLE
completed flexbox exercise

### PR DESCRIPTION
**Pull request by NolanReda**
flex-display
flex-basis
justify-content
align-items

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Nolan, for each of your HTML documents be sure to put the `flex-basis` property in a rule set for `.card-wrapper` instead of `#card-deck` as `flex-basis` is only active on children of a `flex` container.

**Comment by NolanReda** [comment]
flex-wrap changes

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Ok, great! Similar to your `flex-wrap.html`, all of the places that you are using `flex-basis` should be applied to the `.card-wrapper` rule set instead of the `#card-deck`, since `flex-basis` only works on elements that are children of an element with `display: flex` applied to it.

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Nolan, I'm not sure if all of your changes got committed, but the last change request wasn't fulfilled.
https://github.com/NolanReda/prep-0222-code-solutions/pull/8/commits/9ba56d9762503687f9edeee3478d6ec110feae7e

> Ok, great! Similar to your `flex-wrap.html`, all of the places that you are using `flex-basis` should be applied to the `.card-wrapper` rule set instead of the `#card-deck`, since `flex-basis` only works on elements that are children of an element with `display: flex` applied to it.

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
